root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main cmd/server/main.go"
bin = "tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "cmd/verify"]
exclude_regex = ["_test.go"]
delay = 1000