name: buf
on:
  push:
    paths:
      - 'proto/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.22
      - uses: bufbuild/buf-lint-action@v1