name: buf
on:
  push:
    branches:
      - main
    paths:
      - 'proto/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.22.0
      - uses: bufbuild/buf-lint-action@v1
  push:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.22.0
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-push-action@v1.1.1
        with:
          input: 'proto'
          buf_token: ${{ secrets.BUF_TOKEN }}